# Generated by Django 4.2.13 on 2024-05-08 11:27

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('house', models.CharField(max_length=200, verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Наименование')),
                ('model', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Модель')),
                ('release_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата выхода продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('Завод', 'Zavod'), ('ИП', 'Ip'), ('Розничная сеть', 'Rc')], default='Завод', verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('arrears', models.FloatField(blank=True, null=True, verbose_name='Задолженность перед поставщиком')),
                ('release_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('level', models.IntegerField(blank=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chain_stores.contacts', verbose_name='Контакты')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='chain_stores.supplier', verbose_name='Поставщик')),
                ('products', models.ManyToManyField(db_index=True, to='chain_stores.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
