# Generated by Django 4.2.9 on 2024-04-23 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('house', models.CharField(max_length=200, verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Наименование')),
                ('model', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Модель')),
                ('release_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата выхода продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Наименование')),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chain_stores.contacts', verbose_name='Контакты')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain_stores.supplier', verbose_name='Уровень')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain_stores.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
