# Generated by Django 4.2.13 on 2024-05-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_stores', '0002_supplier_supplier_level_alter_supplier_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_level',
            field=models.IntegerField(blank=True, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('Завод', 'Zavod'), ('ИП', 'Ip'), ('Розничная сеть', 'Rc')], default='Завод', verbose_name='Тип'),
        ),
    ]
