# Generated by Django 4.2.13 on 2024-05-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain_stores', '0006_remove_supplier_level_remove_supplier_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='parent',
            field=models.ForeignKey(blank=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='chain_stores.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('Завод', 'Zavod'), ('ИП', 'Ip'), ('Розничная сеть', 'Rc')], default='Завод', verbose_name='Тип'),
        ),
    ]
